spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  # should be 'always' when running for the first time
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: TRACE
mobilele:
  default.admin.pass: ${DEFAULT_ADMIN_PASS:topsecret}
  remember.me.key: ${REMEMBER_ME_KEY:topsecret}

open.exchange.rates:
  schema: https
  host: openexchangerates.org
  path: /api/latest.json
  app_id: ${APP_ID:test}
  symbols: EUR,BGN
  enabled: false

mail:
  mobilele: "mobilele@example.com"
  host: localhost
  port: 1025
  username: ${MAIL_USER:softuni}
  password: ${MAIL_PASSWORD:softuni}